start jupyter in docker

diff --git a/templates/default/dockerImage.sh.erb b/templates/default/dockerImage.sh.erb
--- a/templates/default/dockerImage.sh.erb
+++ b/templates/default/dockerImage.sh.erb
@@ -15,9 +15,9 @@ if [ "$1" == "create" ] ; then
 	echo "Invalid docker file: $2" >&2
 	help
     fi
-    re='^([a-z0-9]+(-[a-z0-9]+)*\.)*[a-z0-9]+\/[a-zA-Z0-9]((?!__)[_a-zA-Z0-9]){0,61}[a-zA-Z0-9]$'
+    re='^([a-z0-9]+(-[a-z0-9]+)*\.)*[a-z0-9]+\/[_a-zA-Z0-9]{0,62}[a-zA-Z0-9]$'
     if ! [[ $3 =~ $re ]] ; then
-	echo "error: Not an image name" >&2
+	echo "error: Not an image name $3" >&2
 	help
     fi
     
@@ -34,9 +34,9 @@ elif [ "$1" == "delete" ] ; then
     docker rmi $2
     
 elif [ "$1" == "list" ] ; then
-    re='^([a-z0-9]+(-[a-z0-9]+)*\.)*[a-z0-9]+\/[a-zA-Z0-9]((?!__)[_a-zA-Z0-9]){0,61}[a-zA-Z0-9]$'
+    re='^([a-z0-9]+(-[a-z0-9]+)*\.)*[a-z0-9]+\/[_a-zA-Z0-9]{0,62}[a-zA-Z0-9]$'
     if ! [[ $2 =~ $re ]] ; then
-	echo "error: Not an image name" >&2
+	echo "error: Not an image name $2" >&2
 	help
     fi
     
diff --git a/templates/default/jupyter.sh.erb b/templates/default/jupyter.sh.erb
--- a/templates/default/jupyter.sh.erb
+++ b/templates/default/jupyter.sh.erb
@@ -8,7 +8,7 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start jupyter_home hadoop_home java_home anaconda_env port logfile secret_dir certs_dir hadoop_username token jupyter_mode] | [kill jupyter_home pid port] | [list] | [kernel-add jupyter_home  project_user conda_environment] [kernel-remove project_user]"
+    echo "usage: $0 [start jupyter_home hadoop_home project_name anaconda_env port logfile secret_dir certs_dir hadoop_username token jupyter_mode image_name] | [kill jupyter_home pid port] | [list] | [kernel-add jupyter_home  project_user conda_environment] [kernel-remove project_user]"
     echo ""
     exit 1
 }
@@ -32,7 +32,7 @@ if [ "$1" == "kill" ] ; then
 
     # Check that the port is an int (and not some injection attack)
     re='^[0-9]+$'
-     if ! [[ $3 =~ $re ]] ; then
+    if ! [[ $3 =~ $re ]] ; then
       echo "error: Not a number" >&2
       help
     fi
@@ -44,7 +44,7 @@ if [ "$1" == "kill" ] ; then
     fi
 
     # Don't kill the pid from this script, as it is run with 'sudo' privileges. Only do it as user 'jupyter'
-    su ${JUPYTER_USER} -c "${DOMAINS_DIR}/domain1/bin/jupyter-kill.sh $2 $3 $4"
+    su ${JUPYTER_USER} -c ${DOMAINS_DIR}/domain1/bin/jupyter-kill.sh $2 $3 $4
 
     # Remove all the directories in the home jupyter folder for this project-user.
     if [ "$2" != "" ] ; then
@@ -56,7 +56,7 @@ if [ "$1" == "kill" ] ; then
     
 elif [ "$1" == "start" ] ; then
 
-    if [ $# -ne 12 ]; then
+    if [ $# -ne 13 ]; then
 	help
     fi
 
@@ -68,10 +68,6 @@ elif [ "$1" == "start" ] ; then
     if [ ! -d "$3" ] ; then
 	echo "Invalid HADOOP_HOME directory: $3"
 	exit 2
-    fi
-    if [ ! -f "${4}/bin/java" ] ; then
-	echo "Invalid JAVA_HOME directory: $4"
-	exit 3
     fi
 
     if [ ! -d "${9}" ] ; then
@@ -85,11 +81,17 @@ elif [ "$1" == "start" ] ; then
       help
     fi
 
+    re='^([a-z0-9]+(-[a-z0-9]+)*\.)*[a-z0-9]+\/[_a-zA-Z0-9]{0,62}[a-zA-Z0-9]$'
+    if ! [[ ${13} =~ $re ]] ; then
+	echo "error: Not an image name ${13}" >&2
+	help
+    fi
+
     pid=$(ps -ef | grep -E "jupyter-(lab|notebook)" | grep "port=$6" | awk '{print $2}')
 
     if [ "$pid" != "" ] ; then
-        su $JUPYTER_USER -c "${DOMAINS_DIR}/domain1/bin/jupyter-kill.sh $2 $pid $6"
-	sleep 5
+	echo "There is already a notebook using this port"
+	exit 1
     fi
 
     # Should look like 'name-4444.log', where '4444' is the port number for the server
@@ -129,12 +131,12 @@ elif [ "$1" == "start" ] ; then
     chmod -R 770 "$2"
      
     # Launch JupyterLab
-    su "${JUPYTER_USER}" -c "${DOMAINS_DIR}/domain1/bin/jupyter-launch.sh $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12}"
+    ${DOMAINS_DIR}/domain1/bin/jupyter-launch.sh $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13}
 
 # list 
 elif [ "$1" == "list" ] ; then
     # This command will output line-separated PIDs for all running jupyter-notebooks into the tmp file, from where it is read by Hopsworks
-    ps -ef | grep -v 'grep' | grep -iE "jupyter-(lab|notebook)" | awk '{print $2}' > /tmp/jupyterNotebookServer.pids
+    ps -ef | grep -v 'grep' | grep -iE "docker run" | grep -iE "jupyter-launcher" | awk '{print $2}' > /tmp/jupyterNotebookServer.pids
 else
   help
 fi
